os: linux
sudo: required

addons:
  apt:
    packages:
      - g++-10
      - gcc-10
      - nasm
    sources:
      - ubuntu-toolchain-r-test

script:
 - g++ --version
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
 - g++ --version
 - gcov --version
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make test ARGS=-V

notifications:
 - email: false
