add_library(ast
        AbstractSyntaxTree.cpp
        AbstractSyntaxTreeBuilder.cpp
        AbstractSyntaxTreeBuilderContext.cpp
        ParseEnvironment.cpp
        VlaExpressionTable.cpp
        ArithmeticExpression.cpp
        ArrayAccess.cpp
        ArrayDeclarator.cpp
        AssignmentExpression.cpp
        BitwiseExpression.cpp
        Block.cpp
        BlockItem.cpp
        ComparisonExpression.cpp
        ConditionalExpression.cpp
        Constant.cpp
        ConstantExpression.cpp
        ContextualSyntaxNodeBuilder.cpp
        CSNB_Creators.cpp
        Declaration.cpp
        DeclarationSpecifiers.cpp
        Declarator.cpp
        DirectDeclarator.cpp
        DoWhileLoopHeader.cpp
        DoubleOperandExpression.cpp
        Expression.cpp
        ExpressionList.cpp
        ExpressionStatement.cpp
        ExternalDeclaration.cpp
        ForInit.cpp
        ForLoopHeader.cpp
        FormalArgument.cpp
        FunctionCall.cpp
        FunctionDeclarator.cpp
        FunctionDefinition.cpp
        GnuExtensions.cpp
        GenericSelection.cpp
        GotoStatement.cpp
        Identifier.cpp
        IdentifierExpression.cpp
        IfStatement.cpp
        InitializedDeclarator.cpp
        JumpStatement.cpp
        LabeledStatement.cpp
        LogicalAndExpression.cpp
        LogicalExpression.cpp
        LogicalOrExpression.cpp
        LoopHeader.cpp
        MemberAccess.cpp
        InitializerListExpression.cpp
        NullStatement.cpp
        LoopStatement.cpp
        ParenthesizedDeclarator.cpp
        Pointer.cpp
        PostfixExpression.cpp
        PrefixExpression.cpp
        ReturnStatement.cpp
        ShiftExpression.cpp
        SingleOperandExpression.cpp
        StorageSpecifier.cpp
        StringLiteralExpression.cpp
        StatementExpression.cpp
        SwitchStatement.cpp
        CaseLabel.cpp
        DefaultLabel.cpp
        TerminalSymbol.cpp
        TypeCast.cpp
        TypeNameExpression.cpp
        CompoundLiteral.cpp
        TypeSpecifier.cpp
        UnaryExpression.cpp
        WhileLoopHeader.cpp
    )

trans_target_defaults(ast)
target_link_libraries(ast PUBLIC parser types symbols scanner)
