add_library(parser
        Action.cpp
        BNFFileReader.cpp
        CanonicalCollection.cpp
        FilePersistedParsingTable.cpp
        FirstTable.cpp
        GeneratedParsingTable.cpp
        Grammar.cpp
        GrammarBuilder.cpp
        LookaheadActionTable.cpp
        LR1Item.cpp
        LR1Parser.cpp
        ParsingTable.cpp
        ParsingTableFile.cpp
        Production.cpp
        TokenStream.cpp
        Action.h
        BNFFileReader.h
        CanonicalCollection.h
        FilePersistedParsingTable.h
        FirstTable.h
        GenerationBuffers.h
        GeneratedParsingTable.h
        HashCombine.h
        Grammar.h
        GrammarBuilder.h
        LookaheadActionTable.h
        LR1Item.h
        LR1Parser.h
        Parser.h
        ParseExtensions.h
        ParsingTable.h
        ParsingTableFile.h
        Production.h
        SyntaxTree.h
        SyntaxTreeBuilder.h
        SyntaxTreeBuilder.cpp
        TokenStream.h)

trans_target_defaults(parser)
target_link_libraries(parser PUBLIC scanner util)
