name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install lcov
      run: sudo apt-get install lcov
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Install nasm
      run: sudo apt install nasm
    - name: create build dir
      run: mkdir build
    - name: cmake
      working-directory: build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: make
      working-directory: build
      run: make
    - name: test
      working-directory: build
      run: make test ARGS="-V"
    - name: coverage
      working-directory: build
      run: make coverage
    - name: prepare coverage
      working-directory: build
      run: cat coverage/*.info >> coverage/lcov.info
    - name: Upload code coverage report to coveralls
      uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage/lcov.info

